package com.vendertool.dal.batchjob;
// default package
// Generated Jul 20, 2013 2:19:14 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchJob generated by hbm2java
 */
@Entity
@Table(name = "batch_job", catalog = "productdb")
public class BatchJob implements java.io.Serializable {

	private long batchJobId;
	private Long accountId;
	private Integer siteId;
	private long fileId;
	private String fileName;
	private Byte status;
	private String reqLocation;
	private String resLocation;
	private String sellerNotes;
	private Byte usecase;
	private Long totalRecords;
	private Long processedRecords;
	private Long errorCount;
	private Date createDate;
	private Date lastModifiedDate;

	public BatchJob() {
	}

	public BatchJob(long batchJobId, long fileId) {
		this.batchJobId = batchJobId;
		this.fileId = fileId;
	}

	public BatchJob(long batchJobId, Long accountId, Integer siteId,
			long fileId, String fileName, Byte status, String reqLocation,
			String resLocation, String sellerNotes, Byte usecase,
			Long totalRecords, Long processedRecords, Long errorCount,
			Date createDate, Date lastModifiedDate) {
		this.batchJobId = batchJobId;
		this.accountId = accountId;
		this.siteId = siteId;
		this.fileId = fileId;
		this.fileName = fileName;
		this.status = status;
		this.reqLocation = reqLocation;
		this.resLocation = resLocation;
		this.sellerNotes = sellerNotes;
		this.usecase = usecase;
		this.totalRecords = totalRecords;
		this.processedRecords = processedRecords;
		this.errorCount = errorCount;
		this.createDate = createDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@Column(name = "batch_job_id", unique = true, nullable = false)
	public long getBatchJobId() {
		return this.batchJobId;
	}

	public void setBatchJobId(long batchJobId) {
		this.batchJobId = batchJobId;
	}

	@Column(name = "account_id")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "site_id")
	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	@Column(name = "file_id", nullable = false)
	public long getFileId() {
		return this.fileId;
	}

	public void setFileId(long fileId) {
		this.fileId = fileId;
	}

	@Column(name = "file_name", length = 256)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "req_location", length = 512)
	public String getReqLocation() {
		return this.reqLocation;
	}

	public void setReqLocation(String reqLocation) {
		this.reqLocation = reqLocation;
	}

	@Column(name = "res_location", length = 512)
	public String getResLocation() {
		return this.resLocation;
	}

	public void setResLocation(String resLocation) {
		this.resLocation = resLocation;
	}

	@Column(name = "seller_notes", length = 512)
	public String getSellerNotes() {
		return this.sellerNotes;
	}

	public void setSellerNotes(String sellerNotes) {
		this.sellerNotes = sellerNotes;
	}

	@Column(name = "usecase")
	public Byte getUsecase() {
		return this.usecase;
	}

	public void setUsecase(Byte usecase) {
		this.usecase = usecase;
	}

	@Column(name = "total_records")
	public Long getTotalRecords() {
		return this.totalRecords;
	}

	public void setTotalRecords(Long totalRecords) {
		this.totalRecords = totalRecords;
	}

	@Column(name = "processed_records")
	public Long getProcessedRecords() {
		return this.processedRecords;
	}

	public void setProcessedRecords(Long processedRecords) {
		this.processedRecords = processedRecords;
	}

	@Column(name = "error_count")
	public Long getErrorCount() {
		return this.errorCount;
	}

	public void setErrorCount(Long errorCount) {
		this.errorCount = errorCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
