package com.vendertool.dal.accountsubscription;

// Generated Jul 6, 2013 10:59:54 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountSubscription generated by hbm2java
 */
@Entity
@Table(name = "account_subscription", catalog = "PRODUCTDB")
public class AccountSubscription implements java.io.Serializable {

	private AccountSubscriptionId id;
	private Long subscriptionId;
	private Short subscriptionType;
	private Date startDate;
	private Date endDate;
	private Date modifyDate;
	private String changeWho;
	private Date createDate;

	public AccountSubscription() {
	}

	public AccountSubscription(AccountSubscriptionId id) {
		this.id = id;
	}

	public AccountSubscription(AccountSubscriptionId id, Long subscriptionId,
			Short subscriptionType, Date startDate, Date endDate,
			Date modifyDate, String changeWho, Date createDate) {
		this.id = id;
		this.subscriptionId = subscriptionId;
		this.subscriptionType = subscriptionType;
		this.startDate = startDate;
		this.endDate = endDate;
		this.modifyDate = modifyDate;
		this.changeWho = changeWho;
		this.createDate = createDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "accountSubscriptionId", column = @Column(name = "ACCOUNT_SUBSCRIPTION_ID", nullable = false, precision = 18, scale = 0)),
			@AttributeOverride(name = "accountId", column = @Column(name = "ACCOUNT_ID", nullable = false, precision = 18, scale = 0)) })
	public AccountSubscriptionId getId() {
		return this.id;
	}

	public void setId(AccountSubscriptionId id) {
		this.id = id;
	}

	@Column(name = "SUBSCRIPTION_ID", precision = 18, scale = 0)
	public Long getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(Long subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@Column(name = "SUBSCRIPTION_TYPE", precision = 4, scale = 0)
	public Short getSubscriptionType() {
		return this.subscriptionType;
	}

	public void setSubscriptionType(Short subscriptionType) {
		this.subscriptionType = subscriptionType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFY_DATE", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "CHANGE_WHO", length = 45)
	public String getChangeWho() {
		return this.changeWho;
	}

	public void setChangeWho(String changeWho) {
		this.changeWho = changeWho;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
