package com.vendertool.dal.accountsubscription;

// Generated Jul 6, 2013 10:59:54 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountSubscriptionId generated by hbm2java
 */
@Embeddable
public class AccountSubscriptionId implements java.io.Serializable {

	private long accountSubscriptionId;
	private long accountId;

	public AccountSubscriptionId() {
	}

	public AccountSubscriptionId(long accountSubscriptionId, long accountId) {
		this.accountSubscriptionId = accountSubscriptionId;
		this.accountId = accountId;
	}

	@Column(name = "ACCOUNT_SUBSCRIPTION_ID", nullable = false, precision = 18, scale = 0)
	public long getAccountSubscriptionId() {
		return this.accountSubscriptionId;
	}

	public void setAccountSubscriptionId(long accountSubscriptionId) {
		this.accountSubscriptionId = accountSubscriptionId;
	}

	@Column(name = "ACCOUNT_ID", nullable = false, precision = 18, scale = 0)
	public long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(long accountId) {
		this.accountId = accountId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountSubscriptionId))
			return false;
		AccountSubscriptionId castOther = (AccountSubscriptionId) other;

		return (this.getAccountSubscriptionId() == castOther
				.getAccountSubscriptionId())
				&& (this.getAccountId() == castOther.getAccountId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAccountSubscriptionId();
		result = 37 * result + (int) this.getAccountId();
		return result;
	}

}
