package com.vendertool.dal.accountmarketplace;

// Generated Jul 7, 2013 3:05:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountMarketplace generated by hbm2java
 */
@Entity
@Table(name = "account_marketplace", catalog = "productdb")
public class AccountMarketplace implements java.io.Serializable {

	private long accountMarketplaceId;
	private Long accountId;
	private Byte mpId;
	private Byte status;
	private String mpClientId;
	private String mpClientSecretCode;
	private String mpToken;
	private Date createDate;

	public AccountMarketplace() {
	}

	public AccountMarketplace(long accountMarketplaceId) {
		this.accountMarketplaceId = accountMarketplaceId;
	}

	public AccountMarketplace(long accountMarketplaceId, Long accountId,
			Byte mpId, Byte status, String mpClientId,
			String mpClientSecretCode, String mpToken, Date createDate) {
		this.accountMarketplaceId = accountMarketplaceId;
		this.accountId = accountId;
		this.mpId = mpId;
		this.status = status;
		this.mpClientId = mpClientId;
		this.mpClientSecretCode = mpClientSecretCode;
		this.mpToken = mpToken;
		this.createDate = createDate;
	}

	@Id
	@Column(name = "ACCOUNT_MARKETPLACE_ID", unique = true, nullable = false)
	public long getAccountMarketplaceId() {
		return this.accountMarketplaceId;
	}

	public void setAccountMarketplaceId(long accountMarketplaceId) {
		this.accountMarketplaceId = accountMarketplaceId;
	}

	@Column(name = "ACCOUNT_ID")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "MP_ID")
	public Byte getMpId() {
		return this.mpId;
	}

	public void setMpId(Byte mpId) {
		this.mpId = mpId;
	}

	@Column(name = "STATUS")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "MP_CLIENT_ID", length = 256)
	public String getMpClientId() {
		return this.mpClientId;
	}

	public void setMpClientId(String mpClientId) {
		this.mpClientId = mpClientId;
	}

	@Column(name = "MP_CLIENT_SECRET_CODE", length = 512)
	public String getMpClientSecretCode() {
		return this.mpClientSecretCode;
	}

	public void setMpClientSecretCode(String mpClientSecretCode) {
		this.mpClientSecretCode = mpClientSecretCode;
	}

	@Column(name = "MP_TOKEN", length = 1000)
	public String getMpToken() {
		return this.mpToken;
	}

	public void setMpToken(String mpToken) {
		this.mpToken = mpToken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_DATE", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

}
