package com.vendertool.dal.batchworklog;
// default package
// Generated Jul 20, 2013 2:19:14 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BatchWorkLog generated by hbm2java
 */
@Entity
@Table(name = "batch_work_log", catalog = "productdb")
public class BatchWorkLog implements java.io.Serializable {

	private long batchWorkLogId;
	private long batchId;
	private long fileId;
	private Long accountId;
	private Long recordId;
	private byte[] request;
	private byte[] response;
	private Byte status;
	private String apiAction;
	private Integer siteId;
	private Date createdDate;
	private Date lastModifiedDate;

	public BatchWorkLog() {
	}

	public BatchWorkLog(long batchWorkLogId, long batchId, long fileId) {
		this.batchWorkLogId = batchWorkLogId;
		this.batchId = batchId;
		this.fileId = fileId;
	}

	public BatchWorkLog(long batchWorkLogId, long batchId, long fileId,
			Long accountId, Long recordId, byte[] request, byte[] response,
			Byte status, String apiAction, Integer siteId, Date createdDate,
			Date lastModifiedDate) {
		this.batchWorkLogId = batchWorkLogId;
		this.batchId = batchId;
		this.fileId = fileId;
		this.accountId = accountId;
		this.recordId = recordId;
		this.request = request;
		this.response = response;
		this.status = status;
		this.apiAction = apiAction;
		this.siteId = siteId;
		this.createdDate = createdDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "batch_work_log_id", unique = true, nullable = false)
	public long getBatchWorkLogId() {
		return this.batchWorkLogId;
	}

	public void setBatchWorkLogId(long batchWorkLogId) {
		this.batchWorkLogId = batchWorkLogId;
	}

	@Column(name = "batch_id", nullable = false)
	public long getBatchId() {
		return this.batchId;
	}

	public void setBatchId(long batchId) {
		this.batchId = batchId;
	}

	@Column(name = "file_id", nullable = false)
	public long getFileId() {
		return this.fileId;
	}

	public void setFileId(long fileId) {
		this.fileId = fileId;
	}

	@Column(name = "account_id")
	public Long getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Long accountId) {
		this.accountId = accountId;
	}

	@Column(name = "record_id")
	public Long getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	@Column(name = "request")
	public byte[] getRequest() {
		return this.request;
	}

	public void setRequest(byte[] request) {
		this.request = request;
	}

	@Column(name = "response")
	public byte[] getResponse() {
		return this.response;
	}

	public void setResponse(byte[] response) {
		this.response = response;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "api_action", length = 64)
	public String getApiAction() {
		return this.apiAction;
	}

	public void setApiAction(String apiAction) {
		this.apiAction = apiAction;
	}

	@Column(name = "site_id")
	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
